// angular/src/app/home/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';
import { switchMap } from 'rxjs/operators';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
})
export class ProfileComponent implements OnInit {
  user$ = this.auth.isAuthenticated$.pipe(switchMap(() => this.auth.user$));

  constructor(public auth: AuthService) {}

  ngOnInit() {}
}

<div *ngIf="user$ | async as user" class="profile-container">
  <ion-avatar class="avatar">
    <img [src]="user.picture" [alt]="user.name" />
  </ion-avatar>
  <h2>{{ user.name }}</h2>
  <p>{{ user.email }}</p>
</div>

// react/src/components/Profile.tsx
import { useAuth0 } from "@auth0/auth0-react";
import { IonAvatar } from "@ionic/react";

const Profile: React.FC = () => {
  const { user, isLoading } = useAuth0();

  if (isLoading) {
    return <div>Loading ...</div>;
  }

  if (!user) return null;

  return (
    <div className="profile-container">
      <IonAvatar className="avatar">
        <img src={user.picture} alt={user.name} />
      </IonAvatar>
      <h2>{user.name}</h2>
      <p>{user.email}</p>
    </div>
  );
};

export default Profile;
